### ISSUE TITLE
无法打开历史会话

### ISSUE THREAD

**Issue by wxyShine** [pengzhile/pandora-cloud-serverless#1]
地址 是这样的时候 卡空白页面  https://pandora-cloud-demo.vercel.app/c/14494b3e-ac5e-44c0-b62b-f50fdd6f9d15

**Comment by pengzhile** [comment]
已修复，演示地址已重新部署。

**Comment by cikichen** [comment]
_next/static/chunks/pages/c/%5BchatId%5D-c0db665988dd1d67.js，一样的因为这个404错误
