### ISSUE TITLE
vecel部署方式，在打开在浏览器侧边栏时是移动端视图，无法使用回车键发送信息

### ISSUE THREAD

**Issue by 1103837067** [pengzhile/pandora-cloud-serverless#18]
如题

**Comment by 1103837067** [comment]
![image](https://github.com/pengzhile/pandora-cloud-serverless/assets/11739977/9ac42557-bd14-412b-b842-b044a93a9ee6)

**Comment by TiMi518** [comment]
要拉宽一点才行，不然会切换成手机版，太廋了就会需要点击飞机才能发送消息
