### ISSUE TITLE
希望可以在页面内查看当前Pandora版本

### ISSUE THREAD

**Issue by RoyRao2333** [pengzhile/pandora-cloud-serverless#21]
大佬你好，刚看到Pandora和Pandora Cloud在两天前更新了版本，我也在两天前部署了Vercel，但是不知道我部署的版本是否是最新版本，以及需要升级与否。

<img width="407" alt="image" src="https://github.com/pengzhile/pandora-cloud-serverless/assets/31413093/387fa3b2-3d2b-4c78-b87a-2eac3ce08eb2">

希望可以在上图所示位置增加一个**Pandora Cloud v0.6.0**之类的标识，非常感谢！

另外如果需要升级的话，我是fork的当前仓库，如果pandora或者pandora-cloud有更新，但是当前仓库没有更新的话，我是不是重新部署Vercel就可以更新到最新版本了呢？谢谢！

**Comment by pengzhile** [comment]
响应header里是有版本的。vercel更新只需要重新部署。
