### ISSUE TITLE
是版本改动了吗，现在vercel不能成功部署了

### ISSUE THREAD

**Issue by Satisfy8375** [pengzhile/pandora-cloud-serverless#23]
![image](https://github.com/pengzhile/pandora-cloud-serverless/assets/95027599/f52846f8-a4ba-46d3-8937-c62f7a0be8e8)

**Comment by pengzhile** [comment]
没有问题，请重试。

**Comment by pengzhile** [comment]
https://pandora-cloud-demo.vercel.app 好好的啊，最新版本了。
