### ISSUE TITLE
【Vercel】无法完整输出长回复

### ISSUE THREAD

**Issue by RoyRao2333** [pengzhile/pandora-cloud-serverless#25]
<img width="821" alt="image" src="https://github.com/pengzhile/pandora-cloud-serverless/assets/31413093/7ce2e965-3a4f-48f7-ad50-8336c97e957f">

Vercel部署，特别是夹带长代码的回复，每次到一半就断了，然后貌似要等云端输出完毕后，刷新页面才能看到整个回复，但是在界面上会报错。

**Comment by pengzhile** [comment]
网络问题，不是vercel的问题。

**Comment by RoyRao2333** [comment]
@pengzhile 

感谢回复，但是很奇怪，换了几个机场和节点都不行，以为是Vercel部署的问题 😂
