### ISSUE TITLE
不挂梯子怎么解决无法获取历史记录和无法对话的问题？（Vercel部署已绑定自己域名，自己域名没有被墙）

### ISSUE THREAD

**Issue by RAiNY7Study** [pengzhile/pandora-cloud-serverless#8]
![1687173580795](https://github.com/pengzhile/pandora-cloud-serverless/assets/128443127/100dad8d-9e05-4ab4-997f-73b7154eab74)
![1687173594205](https://github.com/pengzhile/pandora-cloud-serverless/assets/128443127/bae582c5-9598-4a3a-bf82-55dca5bcfd1c)
如图所示，现在不挂梯子就会报错。对于vercel部署的有没有解决办法？

**Comment by pengzhile** [comment]
> 小白搞了很久，现在解决了这个问题，方法如下：
> 
> 1. 啰嗦一下vercel部署，先直接fork一个这个仓库，然后去vercel部署，最后添加一个自己的域名来访问，例如example.com。
>    ![image](https://user-images.githubusercontent.com/128443127/247043803-c3ea4f05-cbf6-4a41-9284-0af184c4f850.png)
> 2. 根据[官方教程](https://github.com/pengzhile/pandora/blob/master/doc/wiki.md#%E4%BD%BF%E7%94%A8cloudflare-workers%E4%BB%A3%E7%90%86)搞一个CloudFlare代理。
>    ![image](https://user-images.githubusercontent.com/128443127/247044060-cb5bf86a-0491-4e0e-84b3-12bb27edb8d4.png)
> 3. 在CF里添加一个网站，例如刚刚绑定vercel的example.com。选择free就行，其他全部默认就行。
>    ![image](https://user-images.githubusercontent.com/128443127/247044412-82c17df9-ae3b-4802-b250-2230939fcc33.png)
> 4. 添加好了之后返回主页，进入你之前创建的work，然后添加自定义域。比如我自己域名为example.com，我这里填写的是pandora.example.com，然后点击添加就可以了。
>    ![image](https://user-images.githubusercontent.com/128443127/247039240-d708ed66-7d69-457d-b622-cb76633a4295.png)
> 5. 到vercel页面去添加环境变量Key：CHATGPT_API_PREFIX，Value：https://pandora.example.com ，填你刚刚添加的自定义域名。
>    ![image](https://user-images.githubusercontent.com/128443127/247041730-9b024f3e-9cab-4d0f-8510-ffd76a46b08e.png)
> 6. 测试网站，首先是 https://pandora.example.com 应该在非魔法状态下打开，并返回Hello Pandora；其次主域名部署的 https://www.example.com pandora-cloud-serverless项目应该是没有上述问题了的。

赞啊！

**Comment by toniexly** [comment]
呃，没搞懂，如果我绑的是二级域名呢?比如绑的是openai.example.com

**Comment by AjianYo** [comment]
> > 小白搞了很久，现在解决了这个问题，方法如下：
> > 
> > 1. 啰嗦一下vercel部署，先直接fork一个这个仓库，然后去vercel部署，最后添加一个自己的域名来访问，例如example.com。
> >    ![image](https://user-images.githubusercontent.com/128443127/247043803-c3ea4f05-cbf6-4a41-9284-0af184c4f850.png)
> > 2. 根据[官方教程](https://github.com/pengzhile/pandora/blob/master/doc/wiki.md#%E4%BD%BF%E7%94%A8cloudflare-workers%E4%BB%A3%E7%90%86)搞一个CloudFlare代理。
> >    ![image](https://user-images.githubusercontent.com/128443127/247044060-cb5bf86a-0491-4e0e-84b3-12bb27edb8d4.png)
> > 3. 在CF里添加一个网站，例如刚刚绑定vercel的example.com。选择free就行，其他全部默认就行。
> >    ![image](https://user-images.githubusercontent.com/128443127/247044412-82c17df9-ae3b-4802-b250-2230939fcc33.png)
> > 4. 添加好了之后返回主页，进入你之前创建的work，然后添加自定义域。比如我自己域名为example.com，我这里填写的是pandora.example.com，然后点击添加就可以了。
> >    ![image](https://user-images.githubusercontent.com/128443127/247039240-d708ed66-7d69-457d-b622-cb76633a4295.png)
> > 5. 到vercel页面去添加环境变量Key：CHATGPT_API_PREFIX，Value：https://pandora.example.com ，填你刚刚添加的自定义域名。
> >    ![image](https://user-images.githubusercontent.com/128443127/247041730-9b024f3e-9cab-4d0f-8510-ffd76a46b08e.png)
> > 6. 测试网站，首先是 https://pandora.example.com 应该在非魔法状态下打开，并返回Hello Pandora；其次主域名部署的 https://www.example.com pandora-cloud-serverless项目应该是没有上述问题了的。
> 
> 赞啊！

感谢手把手教学，大赞👍
